[29기] 신수녕 회원가입 페이지 추가
wecode-bootcamp-korea/29-1st-KIKEA-frontend pull request #5
Opened 2022-01-28 02:55 UTC by cozynye

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 페이지

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 페이지 UI 완성

2. 회원가입 버튼 클릭시 백엔드와 통신 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
-  span과 label을 이용해 input 애니메이션 이용

<br />

## :: 기타 질문 및 특이 사항
1. 추가사항
- 로그인 제약 조건 추가 / 버튼 클릭 후 회원 가입 완료 시 메인 페이지로 이동 추가
- 라디오 버튼 더 알아보기

2022-01-28 08:41 UTC, younuk23 requested changes
고생하셨습니다 수녕님! 리뷰사항 확인 및 반영해주세요!

2022-01-28 08:41 UTC, younuk23 commented on src/pages/Member/SignUpForm/SignUpForm.js
> +    obj[event.target.value] = event.target.checked;
event.target 구조분해할당해서 쓰는게 더 깔끔하겠네요!

2022-01-28 08:41 UTC, younuk23 commented on src/pages/Member/SignUpForm/SignUpForm.js
> +    console.log(obj);
사이더 코멘트 다 해결해주세요!

2022-01-28 08:41 UTC, younuk23 commented on src/pages/Member/SignUpForm/SignUpForm.js
> +    let obj = {};
```suggestion
    const obj = {
       [value]:checked
    };
```
선언, 프로퍼티 추가 나눠서 하지말고 한번에 가능해보이네요!

2022-01-28 08:41 UTC, younuk23 commented on src/pages/Member/SignUpForm/SignUpForm.js
> +        phone_number: inputState.phoneNumber,
```suggestion
        ...inputState
```
key, value가 동일하다면 단축속성명 및 spread 연산자 조합해서 위와 같이 쓸 수 있겠네요!

2022-01-28 08:41 UTC, younuk23 commented on src/pages/Member/SignUpForm/SignUpForm.js
> +      .then(result => result.access_token);
result.access_token을 return하기만하고 활용하는 부분이 아무것도 없네요!

2022-01-28 08:41 UTC, younuk23 commented on src/pages/Member/SignUpForm/SignUpForm.js
> +      })
```suggestion
      .then(response => response.json())
```

2022-01-31 10:06 UTC, cozynye commented on src/pages/Member/SignUpForm/SignUpForm.js
> +    obj[event.target.value] = event.target.checked;
{value,checked} 이렇게 하는거 말씀이신가요?

2022-02-03 09:05 UTC, merged